### ISSUE TITLE
Fix camera image opening with scroll bars

### ISSUE THREAD

**Issue by chibiconsulting** [jneilliii/OctoPrint-WebcamIframe#11]
Currently, the camera image opens with scroll bars if the camera is larger than the allocated window.

If the same image parameters supplied to the iframe are also applied to the img tag, the image will match the frame without scroll bars.

Example:
`<iframe id="webcam_container" src="/webcam/?action=stream" width="588" height="330" style="border: none;"></iframe>`
`<img style="-webkit-user-select: none;" src="http://10.100.7.21/webcam/?action=stream">`

The img tag should be like this instead with the width and height specified:
`<img style="-webkit-user-select: none;" src="http://10.100.7.21/webcam/?action=stream" width="588" height="330" >`

This would also apply if a smaller camera image is supplied as it would scale to fit the window.

**Comment by jneilliii** [comment]
So I think that img tag you are seeing is not part of this plugin. The plugin only replaces an image tab with an iframe [here](https://github.com/jneilliii/OctoPrint-WebcamIframe/blob/e6796d3db0a4fb43e7c04e7d614e444afb46877e/octoprint_webcam_iframe/static/js/webcam_iframe.js#L15) in the code. I can't control the size of content being loaded in the iframe, so that might be something that you can configure in your camera's web interface/settings some how.
