### ISSUE TITLE
After updating to 0.0.3 I usually get a black image in my iframe

### ISSUE THREAD

**Issue by jpf11** [jneilliii/OctoPrint-WebcamIframe#7]
Once in a while it works, or sometimes I see the stream initial image and then it goes black.  Most of the time it's completely black.  This worked completely fine before the update from the previous version.

**Comment by jneilliii** [comment]
The changes made for this version were to resolve network bandwidth when the control tab was not active or the octoprint web interface wasn't active, like when you are on another browser tab or your browser is minimized. The processes I'm hooking would probably be causing this because it's removing the iframe src and assigning it when the tab becomes active. Could you let me know what browser you are using, and if when you have the control tab active and just minimize your browser and open it back up does the iframe load or when you switch between octoprint tabs?

**Comment by jpf11** [comment]
The experience the same with Chrome on a Windows PC and Samsung Internet on my phone, so I would guess this is browser agnostic.

I reverted to 0.0.2 and everything went back to normal.  If I somehow make free time to troubleshoot this I'll let you know the results, but not likely for a while as I'm amidst too many pending product releases that need my printer.

**Comment by jneilliii** [comment]
Like I mentioned the only differences made between the two versions is removing the iframe src value from the stream to about:blank when the octoprint web interface is not active or the control tab is not active. This is basically the same thing the default image based webcam viewer does. This was specifically to handle @cbc02009 concerns of the webcam being loaded all the time, even if the control tab wasn't active or the browser was minimized, consuming network resources as explained in issue #6. @cbc02009 are you experiencing this same issue with your implementation?

@jpf11 next time this happens, if you don't mind checking your browser's developer console for errors that would be helpful. In chrome that's the F12 key, and look on the console tab. It will not effect your printing capability.

**Comment by cbc02009** [comment]
@jneilliii I see a black screen for a quarter of a second while the stream re-loads, but that's to be expected. I haven't had a single issue with the updated version.

**Comment by jneilliii** [comment]
Is this still an issue? I think one of the recent updates may have made a difference here possibly.
